apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

patches:
  - path: patches/user-service-replicas.yaml
    target:
      kind: Deployment
      name: user-service
  
  - path: patches/authentication-service-replicas.yaml
    target:
      kind: Deployment
      name: authentication-service
  
  - path: patches/order-service-replicas.yaml
    target:
      kind: Deployment
      name: order-service
  
  - path: patches/payment-service-replicas.yaml
    target:
      kind: Deployment
      name: payment-service
  
  - path: patches/gateway-service-replicas.yaml
    target:
      kind: Deployment
      name: gateway-service

  - path: patches/user-service-resources.yaml
    target:
      kind: Deployment
      name: user-service
  
  - path: patches/authentication-service-resources.yaml
    target:
      kind: Deployment
      name: authentication-service
  
  - path: patches/order-service-resources.yaml
    target:
      kind: Deployment
      name: order-service
  
  - path: patches/payment-service-resources.yaml
    target:
      kind: Deployment
      name: payment-service
  
  - path: patches/gateway-service-resources.yaml
    target:
      kind: Deployment
      name: gateway-service