server:
  port: 8084

spring:
  application:
    name: gateway-service

services:
  user-service:
    uri: ${USER_SERVICE_URI}
  authentication-service:
    uri: ${AUTHENTICATION_SERVICE_URI}
  order-service:
    uri: ${ORDER_SERVICE_URI}

security:
  jwt:
    secret_key: ${JWT_SECRET_KEY}
