apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
data:
  USER_SERVICE_URI: http://user-service:8081
  AUTHENTICATION_SERVICE_URI: http://authentication-service:8082
  ORDER_SERVICE_URI: http://order-service:8083
  PAYMENT_SERVICE_URI: http://payment-service:8085
  RANDOM_NUMBER_API_URI: http://www.randomnumberapi.com/api/v1.0/randomnumber
  RANDOM_NUMBER_API_FALLBACK_VALUE: "1"